import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { mkdir, copyFile } from "node:fs/promises";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// When OBSIDIAN_VAULT points at a vault, deploy the built plugin there after
// every build so it can be reloaded (manually, or via the community
// "Hot-Reload" plugin) without a manual copy step.
const vaultPath = process.env.OBSIDIAN_VAULT;

const copyToVaultPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd((result) => {
			if (!vaultPath || result.errors.length > 0) return;
			const pluginDir = path.join(vaultPath, ".obsidian", "plugins", "chronograph");
			void (async () => {
				await mkdir(pluginDir, { recursive: true });
				await Promise.all(
					["main.js", "manifest.json", "styles.css"].map((file) =>
						copyFile(file, path.join(pluginDir, file))
					)
				);
				console.log(`Deployed to ${pluginDir}`);
			})();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [copyToVaultPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
